baseURL = "https://berbah.github.io/"
languageCode = "en-us"
title = "Mapan"
theme = "mapan"
paginate = 5

[params]
  mainSliderButton = "#"

[taxonomies]
  category = "categories"
  tag = "tags"
  promo = "promos"