baseURL = "https://berbah.github.io/"
languageCode = "en-us"
paginate = 5
theme = "mapan"
title = "Mapan"
[[menu.footer]]
identifier = "promos"
name = "Promo"
pre = ""
url = "/promos/"
weight = 5
[[menu.footer]]
identifier = "media"
name = "Media Release"
pre = ""
url = "/media/"
weight = 4
[[menu.footer]]
identifier = "faq"
name = "FAQ"
pre = ""
url = "/faq/"
weight = 3
[[menu.footer]]
identifier = "partnership"
name = "Partner Inquiry"
pre = ""
url = "/layanan/"
weight = 2
[[menu.footer]]
identifier = "about-us"
name = "About Us"
pre = ""
url = "/about-us/"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Blog"
pre = ""
url = "https://www.mapan.id/blog/"
weight = 7
[[menu.main]]
identifier = "faq"
name = "FAQ"
pre = ""
url = "/faq/"
weight = 6
[[menu.main]]
identifier = "partnership"
name = "Partner Inquiry"
pre = ""
url = "/partnership/"
weight = 5
[[menu.main]]
identifier = "media"
name = "Media Release"
pre = ""
url = "/media/"
weight = 4
[[menu.main]]
identifier = "promos"
name = "Promo"
pre = ""
url = "/promos/"
weight = 3
[[menu.main]]
identifier = "layanan"
name = "Layanan"
pre = ""
url = "/layanan/"
weight = 2
[[menu.main]]
identifier = "about-us"
name = "Tentang Mapan"
pre = ""
url = "/about-us/"
weight = 1
[params]
description = "Mapan.id"
[taxonomies]
category = "categories"
promo = "promos"
tag = "tags"
